### ISSUE TITLE
Does release.rb work with ruby3?

### ISSUE THREAD

**Issue by jodygarnett** [GeoWebCache/gwc-release#11]
Working on today's release:
```
ruby release.rb --branch 1.20.x --long-version 1.20.1 --short-version 1.20 --gt-version 26.2 --type stable reset update 
```
```
I, [2022-01-22T22:31:20.672746 #61117]  INFO -- : git '--git-dir=/Users/jgarnett/java/geowebcache/.git' '--work-tree=/Users/jgarnett/java/geowebcache' config '--list'  2>&1
/usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:862:in `encode': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:862:in `command_lines'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:456:in `block in config_list'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:460:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:460:in `config_list'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:430:in `config_remote'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/remote.rb:8:in `initialize'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/base/factory.rb:58:in `new'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/base/factory.rb:58:in `remote'
	from release.rb:421:in `reset'
```

Reading the script and doing the reset by hand shows the same git command problem for update:

```
ruby release.rb --branch 1.20.x --long-version 1.20.1 --short-version 1.20 --gt-version 26.2 --type stable update 
```
```
/usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:862:in `encode': wrong number of arguments (given 3, expected 0..2) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:862:in `command_lines'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:456:in `block in config_list'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:460:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:460:in `config_list'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/lib.rb:430:in `config_remote'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/remote.rb:8:in `initialize'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/base/factory.rb:58:in `new'
	from /usr/local/lib/ruby/gems/3.0.0/gems/git-1.3.0/lib/git/base/factory.rb:58:in `remote'
	from release.rb:232:in `update_for_release'
```

The version of the git library 1.3.0 is understandably quite old and predates ruby 3.

**Comment by jodygarnett** [comment]
Removing lock, and trying `bundle install` again:
```
Fetching net-ssh 6.1.0
Fetching rubyzip 1.3.0
Fetching rchardet 1.8.0
Installing rchardet 1.8.0
Installing rubyzip 1.3.0
Installing net-ssh 6.1.0
Fetching git 1.10.2
Fetching net-scp 3.0.0
Installing git 1.10.2
Installing net-scp 3.0.0
```

That is a much newer version of the ruby git-lib (apparently it has been sometime since I last did this).

**Comment by jodygarnett** [comment]
This resolved the compatibility issue with ruby 3.
